---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/ignite version -o short
    register: ignite_test_output
  - name: ignite version -o short
    debug:
      msg: '{{ ignite_test_output.stdout }}'
