---
- name: resolving vars for {{ weaveworks_ignite_app.name }} {{ weaveworks_ignite_app.version }}
  include_vars:
    file: install-vars.yml
- name: downloading {{ weaveworks_ignite_exe_url }} to {{ weaveworks_ignite_install_exe }}
  become: yes
  become_user: root
  get_url:
    url: '{{ weaveworks_ignite_exe_url }}'
    dest: '{{ weaveworks_ignite_install_exe }}'
    checksum: '{{ weaveworks_ignite_checksum }}'
    mode: 0755
- name: linking {{ weaveworks_ignite_link }} to {{ weaveworks_ignite_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ weaveworks_ignite_install_exe }}'
    dest: '{{ weaveworks_ignite_link }}'
    state: link
